language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $PWD/gradle-3.3/

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    #- android-24
    #- sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  # Gradle
  #- wget http://services.gradle.org/distributions/gradle-3.3-bin.zip
  #- unzip -n gradle-3.3-bin.zip
  #- export GRADLE_HOME=$PWD/gradle-3.3
  #- export PATH=$GRADLE_HOME/bin:$PATH
  
script: ./gradlew app:check

