language: android
jdk: oraclejdk7
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    #- $HOME/.gradle/caches/
    #- $HOME/.gradle/wrapper/
    - $PWD/gradle-2.14.1  

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-23
    #- android-24
    #- sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  # Gradle
  #- wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  #- unzip gradle-2.14.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  
script: gradle sample:assembleRelease

